"""initial_schema

Revision ID: 1870a4bab640
Revises:
Create Date: 2026-10-09 02:54:53.245471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1870a4bab640"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("plan", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tenants_slug"), ["slug"], unique=True)

    op.create_table(
        "vendors",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("vendor_code", sa.String(length=64), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("payment_terms", sa.String(length=64), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "vendor_code", name="uq_tenant_vendor_code"),
    )
    with op.batch_alter_table("vendors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vendors_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_vendors_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_vendors_vendor_code"), ["vendor_code"], unique=False)

    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=20), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("classification", sa.String(length=50), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("doc_type", sa.String(length=50), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("acl_roles_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("knowledge_documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_knowledge_documents_doc_type"), ["doc_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_knowledge_documents_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_knowledge_documents_title"), ["title"], unique=False)

    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("po_number", sa.String(length=64), nullable=False),
        sa.Column("vendor_id", sa.String(length=64), nullable=False),
        sa.Column("vendor_name", sa.String(length=255), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "po_number", name="uq_tenant_po_number"),
    )
    with op.batch_alter_table("purchase_orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_purchase_orders_po_number"), ["po_number"], unique=False)
        batch_op.create_index(batch_op.f("ix_purchase_orders_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_purchase_orders_vendor_id"), ["vendor_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_tenant_user_email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("before_state", sa.Text(), nullable=True),
        sa.Column("after_state", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("workflow_run_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("previous_event_hash", sa.String(length=64), nullable=True),
        sa.Column("event_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_entity_type"), ["entity_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "document_extractions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("schema_type", sa.String(length=50), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=False),
        sa.Column("structured_data", sa.Text(), nullable=False),
        sa.Column("field_confidences", sa.Text(), nullable=False),
        sa.Column("validation_findings", sa.Text(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_extractions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_extractions_document_id"), ["document_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_document_extractions_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "document_pages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("image_path", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_pages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_pages_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_document_pages_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "invoices",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=True),
        sa.Column("invoice_number", sa.String(length=64), nullable=False),
        sa.Column("vendor_id", sa.String(length=64), nullable=True),
        sa.Column("vendor_name", sa.String(length=255), nullable=False),
        sa.Column("po_number", sa.String(length=64), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("variance_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("variance_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("validation_status", sa.String(length=50), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "invoice_number", name="uq_tenant_invoice_number"),
    )
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_invoices_invoice_number"), ["invoice_number"], unique=False)
        batch_op.create_index(batch_op.f("ix_invoices_po_number"), ["po_number"], unique=False)
        batch_op.create_index(batch_op.f("ix_invoices_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding_json", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["knowledge_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("knowledge_chunks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_knowledge_chunks_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_knowledge_chunks_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "purchase_order_lines",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("po_id", sa.String(length=64), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=True),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["po_id"], ["purchase_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchase_order_lines", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_purchase_order_lines_po_id"), ["po_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_purchase_order_lines_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("current_step", sa.String(length=100), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("failure_code", sa.String(length=50), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workflow_runs_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_idempotency_key"), ["idempotency_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("usage_source", sa.String(length=50), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_runs_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_runs_workflow_run_id"), ["workflow_run_id"], unique=False)

    op.create_table(
        "invoice_lines",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("invoice_id", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("tax", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=True),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("invoice_lines", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_invoice_lines_invoice_id"), ["invoice_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_invoice_lines_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "review_tasks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("assigned_to_user_id", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assigned_to_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_tasks_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_tasks_priority"), ["priority"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_tasks_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_tasks_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "workflow_steps",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=64), nullable=False),
        sa.Column("step_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("input_state", sa.Text(), nullable=True),
        sa.Column("output_state", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflow_steps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workflow_steps_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_steps_workflow_run_id"), ["workflow_run_id"], unique=False)

    op.create_table(
        "review_actions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("review_task_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("field_diffs", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["review_task_id"], ["review_tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_actions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_actions_review_task_id"), ["review_task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_actions_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_actions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "tool_calls",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("agent_run_id", sa.String(length=64), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("input_json", sa.Text(), nullable=False),
        sa.Column("output_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tool_calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tool_calls_agent_run_id"), ["agent_run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tool_calls_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tool_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tool_calls_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_tool_calls_agent_run_id"))

    op.drop_table("tool_calls")
    with op.batch_alter_table("review_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_actions_user_id"))
        batch_op.drop_index(batch_op.f("ix_review_actions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_review_actions_review_task_id"))

    op.drop_table("review_actions")
    with op.batch_alter_table("workflow_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_steps_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_steps_tenant_id"))

    op.drop_table("workflow_steps")
    with op.batch_alter_table("review_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_tasks_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_review_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_review_tasks_priority"))
        batch_op.drop_index(batch_op.f("ix_review_tasks_document_id"))

    op.drop_table("review_tasks")
    with op.batch_alter_table("invoice_lines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invoice_lines_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_invoice_lines_invoice_id"))

    op.drop_table("invoice_lines")
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_runs_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_tenant_id"))

    op.drop_table("agent_runs")
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_runs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_status"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_idempotency_key"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_document_id"))

    op.drop_table("workflow_runs")
    with op.batch_alter_table("purchase_order_lines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_order_lines_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_order_lines_po_id"))

    op.drop_table("purchase_order_lines")
    with op.batch_alter_table("knowledge_chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_chunks_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_knowledge_chunks_document_id"))

    op.drop_table("knowledge_chunks")
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invoices_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_invoices_po_number"))
        batch_op.drop_index(batch_op.f("ix_invoices_invoice_number"))

    op.drop_table("invoices")
    with op.batch_alter_table("document_pages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_pages_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_document_pages_document_id"))

    op.drop_table("document_pages")
    with op.batch_alter_table("document_extractions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_extractions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_document_extractions_document_id"))

    op.drop_table("document_extractions")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_entity_type"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("purchase_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_orders_vendor_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_orders_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_orders_po_number"))

    op.drop_table("purchase_orders")
    with op.batch_alter_table("knowledge_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_documents_title"))
        batch_op.drop_index(batch_op.f("ix_knowledge_documents_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_knowledge_documents_doc_type"))

    op.drop_table("knowledge_documents")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_documents_status"))

    op.drop_table("documents")
    with op.batch_alter_table("vendors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vendors_vendor_code"))
        batch_op.drop_index(batch_op.f("ix_vendors_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_vendors_name"))

    op.drop_table("vendors")
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenants_slug"))

    op.drop_table("tenants")
    # ### end Alembic commands ###
