"""add_outbox_and_invoice_doc_unique

Revision ID: df321560da3f
Revises: 1870a4bab640
Create Date: 2026-10-09 13:05:20.167698

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df321560da3f"
down_revision: Union[str, Sequence[str], None] = "1870a4bab640"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_outbox",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_outbox", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_outbox_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_document_outbox_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_document_outbox_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_document_outbox_workflow_run_id"), ["workflow_run_id"], unique=False)

    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_tenant_document_id", ["tenant_id", "document_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_constraint("uq_tenant_document_id", type_="unique")

    with op.batch_alter_table("document_outbox", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_outbox_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_document_outbox_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_document_outbox_status"))
        batch_op.drop_index(batch_op.f("ix_document_outbox_document_id"))

    op.drop_table("document_outbox")
    # ### end Alembic commands ###
